config/routes.rb
Picross::Application.routes.draw do
	resources :puzzles

	root 'puzzles#index'

	resource :rules, :only => [:show]

	namespace :json, constraints: { format: 'json' }  do

		resources :puzzles do
			member do 
				get :getboard
			end

			member do
				get :getfilled
			end
		end
	end
end

app/models/cell.rb
class Cell < ActiveRecord::Base
	belongs_to :puzzle
end

app/models/puzzle.rb
class Puzzle < ActiveRecord::Base
	has_many :cells
	attr_reader :puzzle_array, :filled_cells, :counts, :max_cell_count_x, :max_cell_count_y, :cell_size, :board_width, :cell_width, :border, :row_counts_width, :column_counts_height, :row_counts_height, :row_count_max, :column_count_max


	# Get the filled cells for the puzzle
	def get_cells
		@filled_cells = Cell.where(puzzle_id: self.id)
	end

	# Prepares a 2D array of the appropriate size
	# Each value in the array is 0
	def ready_array
		@puzzle_array = []
		xsize = self.x_size 
		ysize = self.y_size
		ysize.times do
			row_array = []
			xsize.times do
				row_array << 0
			end
			@puzzle_array << row_array
		end
		puts @puzzle_array
	end

	# Adjusts the 2D array to contain the filled cells
	# Filled cells have a value of 1
	def populate_array
		@filled_cells.each do |c|
			x = c[:x]
			y = c[:y]
			@puzzle_array[y][x] = 1
		end
	end

	# Need a method to count blocks of filled cells for each row in a 2DArray
	def check_counts(puzzle_array)
		row_counts = []
		row_length = self.y_size

		puzzle_array.each do |a|
			row_array = []
			count = 0
			checked = 0
			
			a.each do |v|
				checked += 1
				if v == 1
					count += 1

					if checked == row_length
						row_array << count
						count = 0
					end
				elsif v == 0 && count != 0
					row_array << count
					count = 0
				end
			end
			row_counts << row_array
		end
		@counts << row_counts
	end

	def set_cell_size

		if self.x_size >= self.y_size
			cell_count = self.x_size
		else
			cell_count = self.y_size
		end

		case cell_count
		when 5
			@cell_size = 60
		when 10
			@cell_size = 50
		when 15
			@cell_size = 40
		when 20
			@cell_size = 30
		when 25
			@cell_size = 20
		end

		@cell_width = @cell_size - (@border * 2)
	end

	def get_max_cell_count_x
		@row_count_max = 0
		@counts[0].each do |a|
			if a.length > @row_count_max
				@row_count_max = a.length
			end
		end
		@max_cell_count_x = @row_count_max + self.x_size

		@column_count_max = 0
		@counts[1].each do |a|
			if a.length > @column_count_max
				@column_count_max = a.length
			end
		end
		@max_cell_count_y = @column_count_max + self.y_size
	end

	def set_board_size
		@board_width = @max_cell_count_x * @cell_size
		@board_height = @max_cell_count_y * @cell_size
		@row_counts_width = @row_count_max * @cell_size
		@row_counts_height = self.y_size * @cell_size
		@column_counts_height = @column_count_max * @cell_size
	end

	def set_sizes
		@border = 1
		set_cell_size
		get_max_cell_count_x
		set_board_size
	end

	# Gets the counts for row and columns
	def get_counts
		@counts = []
		check_counts(@puzzle_array)
		new_array = @puzzle_array.transpose
		check_counts(new_array)
	end

	# Called by the controller to prepare the game board for play
	# Method call order is important
	def setup_board
		get_cells
		ready_array
		populate_array
		get_counts
		set_sizes	
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		@puzzles = Puzzle.all
	end

end

app/controllers/json/puzzles_controller.rb
class Json::PuzzlesController < ApplicationController

	def getboard
		puzzle = Puzzle.find(params[:id])
		puzzle.setup_board
		board = puzzle.puzzle_array

		render json: [board]
	end

	def getfilled
		puzzle = Puzzle.find(params[:id])
		puzzle.setup_board
		filled = puzzle.filled_cells.length

		render json: [filled]
	end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController

	def index
		@puzzles = Puzzle.all
	end

	def show
		@puzzle = Puzzle.find(params[:id])
		@puzzle.setup_board
	end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController

	def show
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.erb
index erb son

<ul>
	<% @puzzles.each do |p|%>
		<li><%= link_to "#{p.name}", puzzle_path(p[:name]) %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picross</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puzzles/index.erb
<div id="menu">
	<center><%= link_to "How to play", rules_path %></center>
</div>

<div id="puzzle-list">
	<% @puzzles.each do |p|%>
		<div class="puzzle-link">
			<div class="puzzle-name"><%= link_to "#{p.name}", puzzle_path(p[:id]) %></div>
			<div class="puzzle-size"><%= link_to "#{p.x_size}x#{p.y_size}", puzzle_path(p[:id]) %></div>
		</div>
	<% end %>
</div>

app/views/puzzles/show.erb
<% px = @puzzle.x_size %>
<% py = @puzzle.y_size %>
<% pc = @puzzle.counts %>

<div class="topbar">
	<div style="float:left">
	<%= @puzzle.name %><br>
	<%= px.to_s + "x" + py.to_s %>
	</div>

	<div style="float:right">
		Lives: <section id="lives"></section>
	</div>
</div>

<center><div class="gameboard" style=<%= "width:#{@puzzle.board_width + 1}px" %>>
	<div class="column-counts" style='<%= "float:right; height:#{@puzzle.column_counts_height}px; width:100%; padding-right:1px" %>'>
		<% pc[1].reverse.each do |a| %>
			<div class="column-count-column" style='<%= "height:100%; width:#{@puzzle.cell_size}px; float:right; position:relative" %>'>
				<% bottom_value = 0 %>
				<% a.reverse.each do |c| %>
					<div class="count-cell"style="width:<%= @puzzle.cell_width %>px; height: <%= @puzzle.cell_width %>px; border: <%= @puzzle.border %>px solid; position:absolute; bottom: <%= bottom_value %>px"><%= c %></div>
					<% bottom_value += @puzzle.cell_size %>
				<% end %>
			</div>
		<% end %>
	</div>

	<div class="row-counts" style='<%= "float:left; clear:both; height:#{@puzzle.row_counts_height}px; width:#{@puzzle.row_counts_width}px" %>'>
		<% pc[0].each do |a| %>
			<div class="row-count-row" style="float:right; width: 100%">
				<% a.reverse.each do |c| %>
					<div class="count-cell" style="width:<%= @puzzle.cell_width %>px; height: <%= @puzzle.cell_width %>px; border: <%= @puzzle.border %>px solid black;"><%= c %></div>
				<% end %>
			</div>
		<% end %>
	</div>

	<div class="grid">
	<% ci = 0 %>
	<% py.times do |r| %>
		<div class="column" style="float: left;">
			<% ri = 0 %>
			<% px.times do |c| %>
				<div class="cell" id= <%= "x" + ci.to_s + "y" + ri.to_s %> style="width:<%= @puzzle.cell_width %>px; height: <%= @puzzle.cell_width %>px; border: <%= @puzzle.border %>px solid;"></div>
				<% ri += 1 %>
			<% end %>
			<% ci += 1 %>
		</div>
	<% end %>
	</div>
</div></center>

app/views/rules/show.html.erb
<article>
	<ul>
		<li>The numbers on the top and left of the game board give clues about the columns and rows respectively.</li>
		<li>The numbers indicate groups of filled cells in a row or column.</li>
		<li>Each grouping will be separated by at least one empty cell.</li>
		<li>Groupings will appear in the order they are displayed.</li>
		<li>You can hold the ctrl key while clicking to flag cells you are unsure about.</li>
		<li>Making an incorrect guess will cause the loss of one life.</li>
		<li>A fully solved puzzle will reveal a picture.</li>
	</ul>
</article>